services: mongodb
rvm:
  - rbx-19mode
  - 1.9.3
  - 1.8.7
  - 1.9.2
  - 2.0.0
  - jruby-18mode
  - jruby-19mode

notifications:
  recipients:
    - envygeeks@gmail.com

branches:
  only:
    - master
